### ISSUE TITLE
License and contributor covenant

### ISSUE THREAD

**Issue by pjfitzgibbons** [almnt/guide-to-allyship#8]
HI,  I've been reading and learning.
I notice the repo does not have a license or contributor-covenant.  In our new world, having at least a Creative-Commons declaration and a Contributor-Covenant would encourage others to both spread the word and offer contributions.

I'm happy to draft these... just wanted to get your thoughts on the idea.

Looking for your input,
Peter Fitzgibbons

**Comment by almnt** [comment]
Hi Peter,

My apologies for the delay. I super appreciate you pointing this out. I think that’s a great idea and honestly welcome any and all help.

Let me know what you’d need me to do, as well. 😄

**Comment by thatrobotdev** [comment]
Hello @almnt! I would also support this move!

Here is how to add a license to your repository on GItHub- https://help.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository. 

https://choosealicense.com/ is a really good tool for choosing a license for this repo. Choosing a license will help contributors feel good about dedicating their contributions to the rest of the community. My preferred choice would be the MIT License (https://choosealicense.com/licenses/mit/), a permissive license that essentially gives back all edits to the rest of the community for all manners of re-use and distribution with protections for the authors.

A contributor-covenant (or Code of Conduct), is a document that outlines the expectations of contributors in their contributions, as well as their conduct in and outside of the project to be followed in the community. 

https://www.contributor-covenant.org/ has a really good one that you can use on your project, and it comes with clear expectations about creating a harassmen-free space, as well as sample enforcement guidelines for those who break the conduct rules. (https://www.contributor-covenant.org/version/2/0/code_of_conduct/)

The contributor covenant has been adopted by many big and small communities on GitHub to keep these spaces safe and welcoming for anyone.

Please don't hesitate to ask me any questions about how to implement these into your project, because I feel that a guide to allyship is really important to our world!

Thank you 😄

**Comment by almnt** [comment]
This is amazing @thatrobotdev ! I'll work to incorporate this over the next week or so.

**Comment by almnt** [comment]
@thatrobotdev Just added a license and contributor covenant and a few other things. Thanks so much for your guidance and that push. 😄
